[build]
  # Directory to change to before starting build
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist"
  
  # Directory with the serverless functions (we're excluding this)
  # functions = "functions"

# Ignore the functions directory entirely
[build.ignore]
  # This tells Netlify to ignore changes in the functions directory
  # when determining if a build is needed
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)functions'"

# Node.js version
[build.environment]
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200