[build]
  # Directory to change to before starting build
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist"
  
  # Don't specify functions directory to avoid Netlify trying to build them

# Node.js version
[build.environment]
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200